# Generated by Django 4.1.3 on 2022-11-19 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_alter_listing_date_posted_alter_listing_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="date_posted",
        ),
    ]
