# Generated by Django 4.1.3 on 2022-11-19 21:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_remove_listing_date_posted"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="date_posted",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
