# Generated by Django 4.1.3 on 2022-11-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0004_listing_date_posted"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="picture1",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
